version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.9.4

    working_directory: ~/myRepository

    steps:
      - checkout

      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "requirements.txt" }}
            - v1-dependencies-

      - run:
          name: install dependencies
          command: |
            python3.9 -m pip install --upgrade pip
            python3.9 -m pip install --user -r requirements.txt
